## Ejemplo multiplicación de matrices

In [1]:
import numpy as np

Dadas las matriz A=$\begin{pmatrix}
4 & 2 & 1\\
1 & 0 & 3
\end{pmatrix}$
y B=$\begin{pmatrix}
3 & 1\\
1 & 1\\
1 & 2
\end{pmatrix}$. Hallar A $\cdot$ B:

In [2]:
A = np.array([[4,2,1],[1,0,3]])
B = np.array([[3,1],[1,1],[1,2]])

In [3]:
A

array([[4, 2, 1],
       [1, 0, 3]])

In [4]:
B

array([[3, 1],
       [1, 1],
       [1, 2]])

Chequeamos que los tamaños permitan la multiplificación (la matriz resultante sería 2x2)

In [5]:
A.shape

(2, 3)

In [6]:
B.shape

(3, 2)

In [7]:
A@B

array([[15,  8],
       [ 6,  7]])

### Ejercicio 1
$Calcular:
\begin{pmatrix}
1 & 3 & 1\\
1 & 0 & 3\\
1 & -1 & 1
\end{pmatrix}
\cdot
\begin{pmatrix}
1 & 2 & 3\\
3 & -3 & 1\\
2 & 3 & 1
\end{pmatrix}
$

In [8]:
A = np.array([[1,3,1],[1,0,3],[1,-1,1]])
B = np.array([[1,2,3],[3,-3,1],[2,3,1]])
A, B, A@B

(array([[ 1,  3,  1],
        [ 1,  0,  3],
        [ 1, -1,  1]]),
 array([[ 1,  2,  3],
        [ 3, -3,  1],
        [ 2,  3,  1]]),
 array([[12, -4,  7],
        [ 7, 11,  6],
        [ 0,  8,  3]]))

### Ejercicio 2
$Calcular: \begin{pmatrix}
3 & 2 & 1\\
3 & 2 & 1\\
2 & -1 & 1
\end{pmatrix}
\cdot
\begin{pmatrix}
1 \\
-1 \\
-2
\end{pmatrix}
$

In [9]:
A = np.array([[3,2,1],[3,2,1],[2,-1,1]])
B = np.array([[1],[-1],[-2]])
A, B, A@B

(array([[ 3,  2,  1],
        [ 3,  2,  1],
        [ 2, -1,  1]]),
 array([[ 1],
        [-1],
        [-2]]),
 array([[-1],
        [-1],
        [ 1]]))

### Ejercicio 3
$Calcular: \begin{pmatrix}
-2 & \frac{1}{2} & 4\\
2 & 4 & -1\\
2 & -1 & 3
\end{pmatrix}
\cdot
\begin{pmatrix}
2 & 4 & 1\\
-1 & 2 & 4\\
2 & -2 & 1
\end{pmatrix}
$

In [10]:
A = np.array([[-2,0.5,4],[2,4,-1],[2,-1,3]])
B = np.array([[2,4,1],[-1,2,4],[2,-2,1]])
A, B, A@B

(array([[-2. ,  0.5,  4. ],
        [ 2. ,  4. , -1. ],
        [ 2. , -1. ,  3. ]]),
 array([[ 2,  4,  1],
        [-1,  2,  4],
        [ 2, -2,  1]]),
 array([[  3.5, -15. ,   4. ],
        [ -2. ,  18. ,  17. ],
        [ 11. ,   0. ,   1. ]]))

### Ejercicio 4

In [1]:
import numpy as np
A = np.array([[2,4,5],[0,3,-2]])
B = np.array([[0,1,-1],[1,-2,2],[3,0,-1]])
A, B, A@B

(array([[ 2,  4,  5],
        [ 0,  3, -2]]),
 array([[ 0,  1, -1],
        [ 1, -2,  2],
        [ 3,  0, -1]]),
 array([[19, -6,  1],
        [-3, -6,  8]]))