In [1]:
import numpy as np
from numpy.linalg import inv, det

In [2]:
P = np.array([[1,2,1],[3,2,1],[2,3,2]])
P

array([[1, 2, 1],
       [3, 2, 1],
       [2, 3, 2]])

In [3]:
inv(P).round(2)

array([[-0.5,  0.5, -0. ],
       [ 2. , -0. , -1. ],
       [-2.5, -0.5,  2. ]])

In [4]:
J = np.array([[-1,0,0],[0,2,0],[0,0,1]])
J

array([[-1,  0,  0],
       [ 0,  2,  0],
       [ 0,  0,  1]])

In [5]:
inv(J)

array([[-1. , -0. , -0. ],
       [ 0. ,  0.5,  0. ],
       [ 0. ,  0. ,  1. ]])

In [6]:
B = inv(P) @ inv(J)
B.round(2)

array([[ 0.5 ,  0.25, -0.  ],
       [-2.  , -0.  , -1.  ],
       [ 2.5 , -0.25,  2.  ]])

In [7]:
inv(B)

array([[-1., -2., -1.],
       [ 6.,  4.,  2.],
       [ 2.,  3.,  2.]])

In [8]:
A = P @ J @ inv(P)
A

array([[ 6., -1., -2.],
       [ 7., -2., -2.],
       [ 8., -2., -2.]])

In [9]:
det(A @ A).round(2)

4.0

In [10]:
det(A).round(2) ** 2

4.0