In [1]:
import numpy as np
from numpy.linalg import inv, det

$ A^2(X+B)=C^T$

In [2]:
A = np.array([[1,3],[-2,4]])
B = np.array([[2,-1],[0,2]])
C = np.array([[1,-1],[0,2]])

In [3]:
A2 = A@A
A2

array([[ -5,  15],
       [-10,  10]])

In [4]:
det(A2)

100.00000000000004

In [5]:
C.T

array([[ 1,  0],
       [-1,  2]])

In [6]:
inv(A2)

array([[ 0.1 , -0.15],
       [ 0.1 , -0.05]])

In [7]:
X=(inv(A2) @ C.T ) - B
X

array([[-1.75,  0.7 ],
       [ 0.15, -2.1 ]])

In [8]:
A2 @ (X+B)

array([[ 1.00000000e+00, -1.11022302e-15],
       [-1.00000000e+00,  2.00000000e+00]])

In [9]:
C.T

array([[ 1,  0],
       [-1,  2]])

In [10]:
inv(A2)@C.T

array([[ 0.25, -0.3 ],
       [ 0.15, -0.1 ]])

In [11]:
A = np.array([[1,0,1],[1,1,0],[0,1,1]])
B = A - np.eye(3)
B

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [12]:
B@B

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])