In [1]:
import numpy as np
from numpy.linalg import inv

Resolver $AX+B=A^2$
\begin{equation}
A = \begin{pmatrix}
1 & 0 & 0\\
1 & 0 & 1\\
0 & 1 & 0
\end{pmatrix}
B = \begin{pmatrix}
1 & 2 & -1\\
-1 & -1 & 0\\
2 & -1 & 1
\end{pmatrix}
\end{equation}

In [2]:
A = np.array([[1,0,0],[1,0,1],[0,1,0]])
B = np.array([[1,2,-1],[-1,-1,0],[2,-1,1]])
A,B

(array([[1, 0, 0],
        [1, 0, 1],
        [0, 1, 0]]),
 array([[ 1,  2, -1],
        [-1, -1,  0],
        [ 2, -1,  1]]))

### Solución

$AX=A^2-B$

$A^{-1}AX=A^{-1}(A^2-B)$

$IX=A^{-1}(A^2-B)$

$X=A^{-1}(A^2-B)$

In [3]:
inv(A) @ ((A @ A) - B)

array([[ 0., -2.,  1.],
       [-1.,  1.,  0.],
       [ 2.,  4., -1.]])

### Pasos intermedios

In [4]:
inv(A)

array([[ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [-1.,  1.,  0.]])

In [5]:
A @ A

array([[1, 0, 0],
       [1, 1, 0],
       [1, 0, 1]])

In [6]:
(A @ A) - B

array([[ 0, -2,  1],
       [ 2,  2,  0],
       [-1,  1,  0]])