### AX=B

In [1]:
import numpy as np
from numpy.linalg import solve

In [6]:
a = 1
A = np.array([[a,0,1],[1,1,0],[0,1,a]])
B = A - np.eye(3,3)

In [3]:
#X = solve(B**2, B.T)
B

array([[-3.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  1., -3.]])

In [4]:
B.T

array([[-3.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0., -3.]])

In [5]:
B@B == B.T

array([[False,  True, False],
       [False,  True,  True],
       [ True, False, False]])