In [15]:
import numpy as np
from numpy.linalg import inv, det

In [16]:
A = np.array([[3,-1],[-2,4]])
A

array([[ 3, -1],
       [-2,  4]])

In [17]:
P = np.array([[1,-1],[1,2]])
D = np.array([[2,0],[0,5]])
inv(P)

array([[ 0.66666667,  0.33333333],
       [-0.33333333,  0.33333333]])

In [20]:
P @ D @ inv(P) # "@" equivale a np.matmul para multiplicar varias matrices

array([[ 3., -1.],
       [-2.,  4.]])