## Generador de ejercicios (desde abajo)

In [13]:
import numpy as np
from numpy.linalg import inv
D = np.array([[1,0,0],[0,2,0],[0,0,-3]])
P = np.random.randint(3,size=(3,3))
print(P)
A = P @ D @ inv(P)
print(A)
es_simetrica = np.array_equal(A, A.T)
es_simetrica

[[0 1 0]
 [2 2 2]
 [2 2 1]]
[[ 2.  0.  0.]
 [ 2. -7.  8.]
 [ 2. -4.  5.]]


False

In [2]:
import numpy as np
from numpy.linalg import inv
a = np.random.randint(5)
b = a + 1
D = np.array([[a,0,0],[0,-a,0],[0,0,1]])
print('Matriz D:')
print(D)
#P = np.random.randint(3,size=(3,3))
print('Matriz P:')
P = np.array([[0,1,1],[0,-1,0],[1,0,1]])
print(P)
A = P @ D @ inv(P)
print('Matriz A:')
print(A)
es_simetrica = np.array_equal(A, A.T)
es_simetrica

Matriz D:
[[0 0 0]
 [0 0 0]
 [0 0 1]]
Matriz P:
[[ 0  1  1]
 [ 0 -1  0]
 [ 1  0  1]]
Matriz A:
[[1. 1. 0.]
 [0. 0. 0.]
 [1. 1. 0.]]


False

In [83]:
D = np.array([[-2,0,0],[0,2,0],[0,0,1]])
P = np.array([[0,-1,1],[0,-1,0],[1,0,1]])
A = P @ D @ inv(P)
print(A)

[[ 1.  1.  0.]
 [ 0.  2.  0.]
 [ 3. -3. -2.]]


In [12]:
es_simetrica = False

while not es_simetrica:
    D = np.array([[np.random.randint(5), 0, 0], [0, np.random.randint(5), 0], [0, 0, np.random.randint(5)]])
    #P = np.random.randint(5, size=(3, 3))
    P = np.array([[0,-1,1],[0,1,0],[1,0,0]])
    print("Matriz P:")
    print(P)
    try:
        A = P @ D @ inv(P)
    except: 
        pass
    print("Matriz A:")
    print(A)
    es_simetrica = np.array_equal(A, A.T)
    if es_simetrica:
        print("La matriz es simétrica.")
    else:
        print("La matriz no es simétrica. Repitiendo...")

Matriz P:
[[ 0 -1  1]
 [ 0  1  0]
 [ 1  0  0]]
Matriz A:
[[4. 3. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
La matriz no es simétrica. Repitiendo...
Matriz P:
[[ 0 -1  1]
 [ 0  1  0]
 [ 1  0  0]]
Matriz A:
[[ 0. -2.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  3.]]
La matriz no es simétrica. Repitiendo...
Matriz P:
[[ 0 -1  1]
 [ 0  1  0]
 [ 1  0  0]]
Matriz A:
[[ 0. -1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  2.]]
La matriz no es simétrica. Repitiendo...
Matriz P:
[[ 0 -1  1]
 [ 0  1  0]
 [ 1  0  0]]
Matriz A:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
La matriz es simétrica.
