## Diagonalización de matrices

In [1]:
import numpy as np
from numpy.linalg import inv, det, matrix_rank

Diagonalizar la matriz A=$\begin{pmatrix}
0 & 0 & 1\\
-4 & 2 & 2\\
-2 & 0 & 3
\end{pmatrix}$

In [2]:
A = np.array([[3,1,0],[1,3,0],[0,0,3]])
A

array([[3, 1, 0],
       [1, 3, 0],
       [0, 0, 3]])

In [3]:
P = np.array([[1,0,1],[1,0,-1],[0,1,0]])
D = np.array([[4,0,0],[0,3,0],[0,0,2]])

In [4]:
P

array([[ 1,  0,  1],
       [ 1,  0, -1],
       [ 0,  1,  0]])

In [5]:
inv(P)

array([[ 0.5,  0.5,  0. ],
       [ 0. ,  0. ,  1. ],
       [ 0.5, -0.5, -0. ]])

In [6]:
P @ D @ inv(P)

array([[3., 1., 0.],
       [1., 3., 0.],
       [0., 0., 3.]])

In [7]:
A @ A @ A

array([[36, 28,  0],
       [28, 36,  0],
       [ 0,  0, 27]])

In [8]:
P @ D**3 @ inv(P)

array([[36., 28.,  0.],
       [28., 36.,  0.],
       [ 0.,  0., 27.]])