In [2]:
import numpy as np
from numpy.linalg import inv, det

In [16]:
A = np.array([[3,-1],[-2,4]])
A

array([[ 3, -1],
       [-2,  4]])

In [17]:
P = np.array([[1,-1],[1,2]])
D = np.array([[2,0],[0,5]])
inv(P)

array([[ 0.66666667,  0.33333333],
       [-0.33333333,  0.33333333]])

In [20]:
P @ D @ inv(P) # "@" equivale a np.matmul para multiplicar varias matrices

array([[ 3., -1.],
       [-2.,  4.]])

## Ejercicio 8 Parte I

In [2]:
A = np.array([[0,0,1],[-4,2,2],[-2,0,3]])
A

array([[ 0,  0,  1],
       [-4,  2,  2],
       [-2,  0,  3]])

In [15]:
D = np.array([[1,0,0],[0,2,0],[0,0,2]])
P = np.array([[1,0,1],[2,1,0],[1,0,2]])

In [16]:
P

array([[1, 0, 1],
       [2, 1, 0],
       [1, 0, 2]])

In [17]:
inv(P)

array([[ 2.,  0., -1.],
       [-4.,  1.,  2.],
       [-1.,  0.,  1.]])

In [18]:
P @ D @ inv(P)

array([[ 0.,  0.,  1.],
       [-4.,  2.,  2.],
       [-2.,  0.,  3.]])

## Generador de ejercicios (desde abajo)

In [169]:
import numpy as np
from numpy.linalg import inv
D = np.array([[1,0,0],[0,2,0],[0,0,3]])
P = np.random.randint(4,size=(3,3))
print(P)
print(P @ D @ inv(P))

[[2 1 0]
 [2 0 3]
 [0 1 0]]
[[ 1.  0.  1.]
 [-2.  3.  2.]
 [ 0.  0.  2.]]


In [1]:
import numpy as np
from numpy.linalg import inv, det
D = np.array([[1,0,0],[0,1,0],[0,0,2]])
P = np.array([[1,0,1],[1,1,1],[0,2,1]])
P @ D @ inv(P)

array([[ 3., -2.,  1.],
       [ 2., -1.,  1.],
       [ 2., -2.,  2.]])