In [1447]:
import numpy as np
from numpy.linalg import inv
D = np.array([[1,0,0],[0,1,0],[0,0,-2]])
P = np.random.randint(3,size=(3,3))
print(P)
print('La matriz es:....')
A = P @ D @ inv(P)
print(A)
#Chequeo
autovalores = np.linalg.eigvals(A)

print("Los autovalores de la matriz A son:", autovalores)

#Autovectores
autovalores, autovectores = np.linalg.eig(A)

for i in range(len(autovalores)):
    print("Autovalor:", autovalores[i])
    print("Autovector asociado:", autovectores[:,i])
    print()

[[0 1 0]
 [2 0 2]
 [1 2 1]]
La matriz es:....


LinAlgError: Singular matrix

In [2]:
import numpy as np
B = np.array([[ 2., -6.,  6.], [ 0., -4.,  6.], [ 0., -3.,  5.]])
print(B)
#Chequeo
autovalores = np.linalg.eigvals(B)

print("Los autovalores de la matriz A son:", autovalores)

[[ 2. -6.  6.]
 [ 0. -4.  6.]
 [ 0. -3.  5.]]
Los autovalores de la matriz A son: [ 2. -1.  2.]


In [3]:
#Autovectores
autovalores, autovectores = np.linalg.eig(B)

for i in range(len(autovalores)):
    print("Autovalor:", autovalores[i])
    print("Autovector asociado:", autovectores[:,i])
    print()

Autovalor: 2.0
Autovector asociado: [1. 0. 0.]

Autovalor: -1.0
Autovector asociado: [-0.66666667 -0.66666667 -0.33333333]

Autovalor: 2.0
Autovector asociado: [ 0.         -0.70710678 -0.70710678]



In [674]:
es_simetrica = np.array_equal(A, A.T)
es_simetrica

False

In [516]:
0.5 ** (1/2)

0.7071067811865476

In [195]:
B = np.array([[ 3., -2., -2.],  [ 2., -1., -2.],  [ 2., -2., -1.]])

In [136]:
def son_todos_enteros(matriz):
    return all(isinstance(elemento, int) for fila in matriz for elemento in fila)

matriz = [[1, 2, 3], [4, 5, 6]]
resultado = son_todos_enteros(matriz)
print(resultado)  # Salida: True

True


In [137]:
print(son_todos_enteros(A))

False
