In [1]:
import numpy as np
from numpy.linalg import inv, matrix_rank, det

In [2]:
A = np.array([[12,-2],[3,-2]])
B = np.array([[-2,2],[12,0]])

In [3]:
A

array([[12, -2],
       [ 3, -2]])

In [20]:
X = inv(A)*det(A)
X

array([[-2.,  2.],
       [-3., 12.]])

In [5]:
B

array([[-2,  2],
       [12,  0]])

In [22]:
X@B

array([[ 28.,  -4.],
       [150.,  -6.]])

In [27]:
1/2*(((4/2*2**2)-2**4/4)-((4/2)-(1/4)))

9.0

In [33]:
8-4-(2-1/4)

2.25

In [34]:
16-7

9

Examen extraordinario

In [1]:
import numpy as np
from numpy.linalg import inv, matrix_rank, det

In [2]:
A = np.array([[8,2],[3,3]])
B = np.array([[0,-4],[8,-3]])
print(A), print(B)

[[8 2]
 [3 3]]
[[ 0 -4]
 [ 8 -3]]


(None, None)

In [13]:
C = -inv(A)@B
C

array([[ 0.88888889,  0.33333333],
       [-3.55555556,  0.66666667]])

In [14]:
C *18

array([[ 16.,   6.],
       [-64.,  12.]])